
DROP DATABASE IF EXISTS LibraryDB;
CREATE DATABASE LibraryDB;
USE LibraryDB;


CREATE TABLE Members (
  MemberID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(100) NOT NULL,
  Email VARCHAR(100),
  PRIMARY KEY (MemberID)
);


CREATE TABLE Books (
  BookID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  Author VARCHAR(100),
  PRIMARY KEY (BookID)
);


CREATE TABLE Borrowed (
  BorrowID INT NOT NULL AUTO_INCREMENT,
  MemberID INT NOT NULL,
  BookID INT NOT NULL,
  BorrowDate DATE,
  ReturnDate DATE,
  PRIMARY KEY (BorrowID),
  FOREIGN KEY (MemberID) REFERENCES Members(MemberID),
  FOREIGN KEY (BookID) REFERENCES Books(BookID)
);